import type { Metadata } from "next";

import "./style.css";
import { Instrument_Sans } from "next/font/google";
const instrument_Sans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Designor",
  description: "Generated by create next app",
  icons: {
    icon: '/svgviewer-output.svg',
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${instrument_Sans.className} antialiased absolute inset-0 -z-10 h-full w-full bg-bgColor bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] `}
      >
        {children}
      </body>
    </html>
  );
}
