import avatar1 from "@/public/avatars/testemonials/1OwzdZHx9ElDw1ZAavs6WGWBSw.avif";
import avatar2 from "@/public/avatars/testemonials/BJytCbStiWSy9rxpQ0wU6I3SNiI.avif";
import avatar3 from "@/public/avatars/testemonials/BRu6MhHhp9NjldqU9TTCEAEoGKg.avif";
import avatar4 from "@/public/avatars/testemonials/Pm9TTOkN341IYtePLdPGmhG0E.avif";
import avatar5 from "@/public/avatars/testemonials/iGk4x1NJSVgWzFvuQQADJp9I.avif";
import avatar6 from "@/public/avatars/testemonials/ikD34vgzaLM6N50MKdcR9HVBnk.avif";
import avatar7 from "@/public/avatars/testemonials/lKaaStgbmdIe8TfrIkFlKzHazV0.avif";
import avatar8 from "@/public/avatars/testemonials/mhC7dhzvLcqmUofPcC2BW8vh4.avif";
import avatar9 from "@/public/avatars/testemonials/ofIUD8MCjke7Xz8jkh29AWqajJo.avif";
import avatar10 from "@/public/avatars/testemonials/qCpU7HJtiveCC9wTFuh7L4wc8YM.avif";

export const testimonials1 = [
    {
      src: avatar1,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar2,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar3,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar4,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar5,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
    {
      src: avatar1,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar2,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar3,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar4,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar5,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
    {
      src: avatar1,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar2,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar3,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar4,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar5,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
    {
      src: avatar1,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar2,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar3,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar4,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar5,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
  ];
  
 export const testimonials2 = [
    {
      src: avatar6,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar7,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar8,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar9,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar10,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
    {
      src: avatar6,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar7,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar8,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar9,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar10,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
    {
      src: avatar6,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar7,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar8,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar9,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar10,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
    {
      src: avatar6,
      description: "Designor unleashes creativity on a new level. Dynamic content generation in Figma? Yes, please!",
      username: "Creative Mind",
      id: "creativemind",
      color: "#ffe1c2",
    },
    {
      src: avatar7,
      description: "Incorporating Designor Framer into our web development process has streamlined collaboration.",
      username: "WebDev Guru",
      id: "webdevguru",
      color: "#ffdbde",
    },
    {
      src: avatar8,
      description: "Designor transformed my workflow with instant suggestions and real-time collaboration. A game-changer!",
      username: "Alex Designs",
      id: "alexDesigns",
      color: "#b0efff",
    },
    {
      src: avatar9,
      description: "Designor's efficiency in generating code snippets is unmatched. Seamless integration, time-saving.",
      username: "Code Master",
      id: "codemaster",
      color: "#ebc9ff",
    },
    {
      src: avatar10,
      description: "Designor is a game changer for our team. We have been able to improve our productivity and collaboration.",
      username: "Olivia Reynolds",
      id: "oliviareynolds",
      color: "#ffbdbd",
    },
  ];